//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNGames.FrontEnd.User {
    
    
    public partial class Betting {
        
        /// <summary>
        /// Skin2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TNGames.Controls.FrontEnd.Skin_BettingWinBoards Skin2;
        
        /// <summary>
        /// Skin1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TNGames.Controls.FrontEnd.Skin_BettingGame Skin1;
        
        /// <summary>
        /// Skin3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TNGames.Controls.FrontEnd.Skin_GeneralNotice Skin3;
        
        /// <summary>
        /// Skin4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TNGames.Controls.FrontEnd.Skin_GeneralNotice Skin4;
        
        /// <summary>
        /// Skin6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TNGames.Controls.FrontEnd.Skin_GeneralNotice Skin6;
        
        /// <summary>
        /// Skin5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TNGames.Controls.FrontEnd.Skin_News Skin5;
    }
}
